server:
  port: 33333
spring:
  application:
    name: cloud-gateway

eureka:
  client:
    register-with-eureka: true #服务注册开关
    fetch-registry: true # 服务发现开关
    service-url: #与注册中心交互，用逗号隔开
      defaultZone: ${EUREKA_SERVER:http://localhost:51010/eureka/}
  instance:
    prefer-ip-address: true #ip注册到eureka
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${SPRING.APPLICATION.NAME}:${SERVER.PORT} #指定实例ip
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger -%msg%n'
zuul:
#  ignored-services: '*'
  sensitive-headers:
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    servers:
       path: /v1/server/**
       service-id: cloud-server1
    consumers:
       path: /v1/con/**
       service-id: cloud-consumer1
