server:
  port: 31600
spring:
  application:
    name: cloud-consumer2
eureka:
  client:
    register-with-eureka: true #服务注册开关
    fetch-registry: true # 服务发现开关
    service-url: #与注册中心交互，用逗号隔开
      defaultZone: ${EUREKA_SERVER:http://localhost:51010/eureka/}
  instance:
    prefer-ip-address: true #ip注册到eureka
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${SPRING.APPLICATION.NAME}:${SERVER.PORT} #指定实例ip
    lease-expiration-duration-in-seconds: 90 #定义服务失效的时间，默认为90秒
    lease-renewal-interval-in-seconds: 30 #定义服务续约任务的调用时间，默认30秒
# 设置ribbon
ribbon:
  ConnectTimeout: 500
  ReadTimeout: 2000
  MaxAutoRetries: 1
  MaxAutoRetiesNetxServer: 2
feign:
  hystrix:
    enabled: false

# 设置全局hystrix